server:
  port: 8091
#  tomcat:
#    threads:
#      max: 10 #tomcat的最大并发值修改为10,默认是200

spring:
  zipkin:
    base-url: http://127.0.0.1:9411/ #zipkin server的请求地址
    discovery-client-enabled: false #让nacos把它当成一个URL，而不要当做服务名
  sleuth:
    sampler:
      probability: 1.0 #采样的百分比 数据采样0.1-1.0之间
  application:
    name: service-order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 1234
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
#      filter:
#        enabled: false
      transport:
        port: 9999 #跟控制台交流的端口,随意指定一个未使用的端口即可
        dashboard: localhost:8080 # 指定控制台服务的地址

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

service-product: # 调用的提供者的名称
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
feign:
  sentinel:
    enabled: true #开启OpenFeign对Sentinel的支持
